### PR TITLE
Speaker

### PR DESCRIPTION
**Pull request by Racheltmz**
Created speaker and speaker sub pages. We will have to work on the styles for the speaker cards (speaker page) and the paragraphs of text (sub pages). Please take a look during your free time and if there are any changes to be made regarding the arrangement please tell me.

### CODE REVIEW

**Comment by PekYC** [comment]
I think the cards and their overlays look great, however I have a few comments:

- Could you make it such that the overlay only happens then it hovers over the image, and not the entire div? 
- Consider making the overlay slightly darker, as it's a bit hard to see the name for some of the speakers, such as the Topic 2 Buddhist Speaker
- On large screens, the speaker's image in the sub pages are off centered
image

**Comment by Racheltmz** [comment]
Ok I'll fix those issues and experiment some of ur suggestions later.

**Comment by Racheltmz** [comment]
- By shadow effect do you mean neumorphism.
- Can you give me the dimensions of your screen so I can try simulate when I'm doing.

**Comment by PekYC** [comment]
> * By shadow effect do you mean neumorphism.
> * Can you give me the dimensions of your screen so I can try simulate when I'm doing.

- Yup, that's what I meant
- I believe my screen dimensions should be 1920px X 1080px   (WxH)

**Pull request merged**
