### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by Racheltmz**
I mainly worked on the home page. These are the changes I've made to the website:
1. Created the structure for the home page
2. Rearranged elements for responsiveness
3. Added styles to the css for the home page
4. Added js code (index.js) so that the video can be displayed in full screen
5. Added footer to all pages
6. Organised the assets folder into a few sub folders (there is a dummy video inside becuz I wanted to test out the video functions)

Note: I randomly chose some colors so they can be replaced. 
If you guys have any feedback pls feel free to mention it

### CODE REVIEW

**Comment by PekYC** [comment]
image

- On bigger screens like mine, this part of the content gets stretched out too much. Is it possible to set a max width for this portion?

- Also, I haven't done my own research, but the javascript function you implemented, is it necessary if we're embedding a youtube video?

**Comment by Racheltmz** [comment]
@PekYC 
I've updated the code, could you check if the max-width code works on your screen. 
For the video, thanks for reminding me that it's a youtube video, I've changed the code from video to iframe

**Comment by PekYC** [comment]
image

The content is off-centered. Would it be simpler if I handle this portion since I can preview the result easier? Just this alignment portion only

**Comment by Racheltmz** [comment]
Yep I think it would be better if u handled it

**Comment by PekYC** [comment]
Done! I think it's ready to be merged now. Did I miss out anything?

 If not, then let this be our base to work with, then Alvin can suggest improvements to the aesthetics.

**Comment by Racheltmz** [comment]
Thanks! Yep we can merge

**Pull request merged**
